name: device_vendor_info_example
description: "Demo Flutter application for fetching hardware informations"
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  device_vendor_info:
    path: ../
  intl: ^0.19.0
dev_dependencies:
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
